### ISSUE TITLE
Replace our custom icon solution with an external package with treeshaking

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-incubator/github-dashboard#11]
At this moment we use create custom components for every icon we propose. Would be great to use an external icon library that 

Acceptance criteria:
- The external library is treeshakable -  unused icons are not part of the bundle
- Has option to customize colors, and icon parameters ( line width and size )
- It has an open source Licens ( MIT -preferred )
- it has to have enough icon diversity so it can cover our app needs
- replace the current icons with the external ones
- (optional) uses Vue 3 syntax

Proposal:
- [IconPark](https://github.com/bytedance/IconPark)

**Comment by valentinvieriu** [comment]
@Nurintaaan would you like to go even further with the icon adjustments?

**Comment by Nurintaaan** [comment]
Sure, I'll take a look later when I have time.
