### ISSUE TITLE
Created Card Component for the overview items

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-incubator/github-dashboard#5]
The overview Items are currently not separate components.
![image](https://user-images.githubusercontent.com/478866/94803812-2c931780-03ea-11eb-82d5-3812a8b6b32c.png)

Extract the code as separate reusable component and update the OverviewPage
Acceptance Criterias:
- Component is using Props to pass the Values
- Component can use Slots to pass in the Icons

**Comment by mbeuil** [comment]
Can I work on this ?

**Comment by valentinvieriu** [comment]
Please do! I will add some more details to the issue, so it can be more obvious the outcome
Happy to have contributors. 
Hope you can manage to see the cards using your own github login

**Comment by resparx** [comment]
hey hi @valentinvieriu , shall i pick this up ?

**Comment by valentinvieriu** [comment]
@resparx Feel free!
