### ISSUE TITLE
Find a reusable icon solution

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-incubator/github-dashboard#6]
At this moment all icons are part of the html as SVG. This is not very reusable and scalable.
Come with a solution, component based, that allows for reusability of icons.

External libraries can be used, they need to be open source and support tree shaking
Fonts can also be used

**Comment by Nurintaaan** [comment]
Hi, I would like to participate in this issue

**Comment by valentinvieriu** [comment]
Sure! Go ahead, you don't have to ask for permissions. @Nurintaaan
