### ISSUE TITLE
Implement search and filtering in the Team section

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-incubator/github-dashboard#7]
We wan to have a search functionality that works for the Team's page, but also can be universally used for other sections. We should use the Vue3 Composition Api to allow for portability of search

The search should only use the local data from the store / component and should not make additional calls to GraphQl api
![image](https://user-images.githubusercontent.com/478866/94805957-7f220300-03ed-11eb-9604-a1f786de8cc4.png)

**Comment by divyavit** [comment]
Hi, I am interested in working on this. Can I start it ?

**Comment by valentinvieriu** [comment]
Sure! The issue is still open!

**Comment by adrikagupta** [comment]
Hey, I would love to work on this. Can you assign it to me?

**Comment by valentinvieriu** [comment]
@adrikagupta Yes, the issue is still open
